# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_user_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Friendships',
            field=models.ManyToManyField(related_name='_user_Friendships_+', to='MainApp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Dateofbirth',
            field=models.CharField(max_length=20),
        ),
    ]
