# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-15 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20180524_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Cause', models.CharField(max_length=255)),
                ('Open_spots', models.IntegerField()),
                ('Types_of_work', models.CharField(max_length=500)),
                ('Start_date', models.DateTimeField()),
                ('Finish_date', models.DateTimeField()),
                ('Description_header', models.CharField(max_length=500)),
                ('Description_main', models.CharField(max_length=500)),
                ('Goles', models.CharField(max_length=500)),
                ('Associated_users', models.ManyToManyField(related_name='associated_user', to='MainApp.User')),
                ('Contributer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contributer_id', to='MainApp.User')),
                ('Organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='MainApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_number', models.IntegerField()),
                ('Street_name', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('State_province', models.CharField(max_length=255)),
                ('Postcode', models.IntegerField()),
                ('County', models.CharField(max_length=30)),
                ('Organizer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organizer_address', to='MainApp.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='User_adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_number', models.IntegerField()),
                ('Street_name', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('State_province', models.CharField(max_length=255)),
                ('Postcode', models.IntegerField()),
                ('County', models.CharField(max_length=30)),
            ],
        ),
    ]
